name: eldorado
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.12.0
  cloud_firestore: ^4.7.0
  flutter_native_splash: ^2.2.19
flutter_native_splash:
  image: assets/logo.png
  color: "#000000"
  fill: false
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/