// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoj344xS-_ryrak8YGxjoUuBGeCw9rAHo',
    appId: '1:188548708194:web:eaf0cf468e21ae6d765e3b',
    messagingSenderId: '188548708194',
    projectId: 'el-dorado-game',
    authDomain: 'el-dorado-game.firebaseapp.com',
    storageBucket: 'el-dorado-game.appspot.com',
    measurementId: 'G-2P6C1B2NQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmI3l06tA85EdkFJdtQV86tbdjjnhK35Q',
    appId: '1:188548708194:android:c48bcb6f7383ff0b765e3b',
    messagingSenderId: '188548708194',
    projectId: 'el-dorado-game',
    storageBucket: 'el-dorado-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv1vpEQztAdySRUCystULPEhxDXKM5-uU',
    appId: '1:188548708194:ios:05056312cb0ad29a765e3b',
    messagingSenderId: '188548708194',
    projectId: 'el-dorado-game',
    storageBucket: 'el-dorado-game.appspot.com',
    iosClientId: '188548708194-cqjlc1n22nfok3snheld8vvodjtbrtc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.elDoradoShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv1vpEQztAdySRUCystULPEhxDXKM5-uU',
    appId: '1:188548708194:ios:44f522a4c7fb5921765e3b',
    messagingSenderId: '188548708194',
    projectId: 'el-dorado-game',
    storageBucket: 'el-dorado-game.appspot.com',
    iosClientId: '188548708194-ls2r9kovkd9smotae3d0t6mh2vov3b76.apps.googleusercontent.com',
    iosBundleId: 'com.example.elDoradoShop.RunnerTests',
  );
}
